version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DATABASE_URL: "pgsql://angel:3553d1-angel@database:5432/postgres"
    depends_on:
      - database
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - app

  database:
    image: postgres:15
    container_name: symfony_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: 3553d1-angel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
